common: &common
  # 一覧に出す最大数
  topic_list_size: 5
  comment_list_size: 5

  # コミュニティのトップで出す数
  cmm_show_list_size: 3

  # コミュニティトピックともに表示するコメントの最大数
  tpc_cmm_comment_list_size_with_comment: 3

  # ポータルで表示する数と期間
  portal_tpc_cmm_latest_topic_size: 3
  portal_tpc_cmm_latest_topic_days: 10
  portal_tpc_cmm_commented_topic_size: 3
  portal_tpc_cmm_commented_topic_days: 10

  # ポータルに表示する場合などのアルバムのキャッシュ時間(sec)
  tpc_topic_cmm_community_cache_time: 600

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common

