---
docomo:
  E63E: sun
  E63F: cloud
  E640: rain
  E641: snow
  E642: thunder
  E643: typhoon
  E644: mist
  E645: sprinkle
  E646: aries
  E647: taurus
  E648: gemini
  E649: cancer
  E64A: leo
  E64B: virgo
  E64C: libra
  E64D: scorpius
  E64E: sagittarius
  E64F: capricornus
  E650: aquarius
  E651: pisces
  E652: sports
  E653: baseball
  E654: golf
  E655: tennis
  E656: soccer
  E657: ski
  E658: basketball
  E659: motorsports
  E65A: pocketbell
  E65B: train
  E65C: subway
  E65D: bullettrain
  E65E: car
  E65F: rvcar
  E660: bus
  E661: ship
  E662: airplane
  E663: house
  E664: building
  E665: postoffice
  E666: hospital
  E667: bank
  E668: atm
  E669: hotel
  E66A: 24hours
  E66B: gasstation
  E66C: parking
  E66D: signaler
  E66E: toilet
  E66F: restaurant
  E670: cafe
  E671: bar
  E672: beer
  E673: fastfood
  E674: boutique
  E675: hairsalon
  E676: karaoke
  E677: movie
  E678: upwardright
  E679: carouselpony
  E67A: music
  E67B: art
  E67C: drama
  E67D: event
  E67E: ticket
  E67F: smoking
  E680: nosmoking
  E681: camera
  E682: bag
  E683: book
  E684: ribbon
  E685: present
  E686: birthday
  E687: telephone
  E688: mobilephone
  E689: memo
  E68A: tv
  E68B: game
  E68C: cd
  E68D: heart
  E68E: spade
  E68F: diamond
  E690: club
  E691: eye
  E692: ear
  E693: rock
  E694: scissors
  E695: paper
  E696: downwardright
  E697: upwardleft
  E698: foot
  E699: shoe
  E69A: eyeglass
  E69B: wheelchair
  E69C: newmoon
  E69D: moon1
  E69E: moon2
  E69F: moon3
  E6A0: fullmoon
  E6A1: dog
  E6A2: cat
  E6A3: yacht
  E6A4: xmas
  E6A5: downwardleft
  E6AC: slate
  E6AD: pouch
  E6AE: pen
  E6B1: shadow
  E6B2: chair
  E6B3: night
  E6B7: soon
  E6B8: on
  E6B9: end
  E6BA: clock
  E6CE: phoneto
  E6CF: mailto
  E6D0: faxto
  E6D1: info01
  E6D2: info02
  E6D3: mail
  E6D4: by-d
  E6D5: d-point
  E6D6: yen
  E6D7: free
  E6D8: id
  E6D9: key
  E6DA: enter
  E6DB: clear
  E6DC: search
  E6DD: new
  E6DE: flag
  E6DF: freedial
  E6E0: sharp
  E6E1: mobaq
  E6E2: one
  E6E3: two
  E6E4: three
  E6E5: four
  E6E6: five
  E6E7: six
  E6E8: seven
  E6E9: eight
  E6EA: nine
  E6EB: zero
  E6EC: heart01
  E6ED: heart02
  E6EE: heart03
  E6EF: heart04
  E6F0: happy01
  E6F1: angry
  E6F2: despair
  E6F3: sad
  E6F4: wobbly
  E6F5: up
  E6F6: note
  E6F7: spa
  E6F8: cute
  E6F9: kissmark
  E6FA: shine
  E6FB: flair
  E6FC: annoy
  E6FD: punch
  E6FE: bomb
  E6FF: notes
  E700: down
  E701: sleepy
  E702: sign01
  E703: sign02
  E704: sign03
  E705: impact
  E706: sweat01
  E707: sweat02
  E708: dash
  E709: sign04
  E70A: sign05
  E70B: ok
  E70C: appli01
  E70D: appli02
  E70E: t-shirt
  E70F: moneybag
  E710: rouge
  E711: denim
  E712: snowboard
  E713: bell
  E714: door
  E715: dollar
  E716: pc
  E717: loveletter
  E718: wrench
  E719: pencil
  E71A: crown
  E71B: ring
  E71C: sandclock
  E71D: bicycle
  E71E: japanesetea
  E71F: watch
  E720: think
  E721: confident
  E722: coldsweats01
  E723: coldsweats02
  E724: pout
  E725: gawk
  E726: lovely
  E727: good
  E728: bleah
  E729: wink
  E72A: happy02
  E72B: bearing
  E72C: catface
  E72D: crying
  E72E: weep
  E72F: ng
  E730: clip
  E731: copyright
  E732: tm
  E733: run
  E734: secret
  E735: recycle
  E736: r-mark
  E737: danger
  E738: ban
  E739: empty
  E73A: pass
  E73B: full
  E73C: leftright
  E73D: updown
  E73E: school
  E73F: wave
  E740: fuji
  E741: clover
  E742: cherry
  E743: tulip
  E744: banana
  E745: apple
  E746: bud
  E747: maple
  E748: cherryblossom
  E749: riceball
  E74A: cake
  E74B: bottle
  E74C: noodle
  E74D: bread
  E74E: snail
  E74F: chick
  E750: penguin
  E751: fish
  E752: delicious
  E753: smile
  E754: horse
  E755: pig
  E756: wine
  E757: shock
kddi:
  E469: typhoon
  E46A: signaler
  E46B: run
  E471: happy01
  E472: angry
  E473: crying
  E475: sleepy
  E476: flair
  E477: heart03
  E478: heart04
  E47A: bomb
  E47C: sandclock
  E47D: smoking
  E47E: nosmoking
  E47F: wheelchair
  E481: danger
  E482: sign01
  E485: snow
  E486: moon3
  E487: thunder
  E488: sun
  E48C: rain
  E48D: cloud
  E48F: aries
  E490: taurus
  E491: gemini
  E492: cancer
  E493: leo
  E494: virgo
  E495: libra
  E496: scorpius
  E497: sagittarius
  E498: capricornus
  E499: aquarius
  E49A: pisces
  E49C: bag
  E49E: ticket
  E49F: book
  E4A0: clip
  E4A1: pencil
  E4A3: atm
  E4A4: 24hours
  E4A5: toilet
  E4A6: parking
  E4AA: bank
  E4AB: house
  E4AC: restaurant
  E4AD: building
  E4AE: bicycle
  E4AF: bus
  E4B0: bullettrain
  E4B1: car
  E4B3: airplane
  E4B4: yacht
  E4B5: train
  E4B6: soccer
  E4B7: tennis
  E4B8: snowboard
  E4B9: motorsports
  E4BA: baseball
  E4BC: spa
  E4BE: slate
  E4C1: wine
  E4C2: bar
  E4C3: beer
  E4C6: game
  E4C7: dollar
  E4C9: xmas
  E4CA: cherryblossom
  E4CE: maple
  E4CF: present
  E4D0: cake
  E4D2: cherry
  E4D5: riceball
  E4D6: fastfood
  E4D8: horse
  E4DB: cat
  E4DC: penguin
  E4DE: pig
  E4E0: chick
  E4E1: dog
  E4E4: tulip
  E4E5: annoy
  E4E6: sweat02
  E4E7: bleah
  E4EB: kissmark
  E4F1: secret
  E4F3: punch
  E4F4: dash
  E4F9: good
  E4FE: eyeglass
  E502: tv
  E503: karaoke
  E504: moneybag
  E505: notes
  E508: music
  E509: rouge
  E50C: cd
  E512: bell
  E513: clover
  E514: ring
  E515: camera
  E516: hairsalon
  E517: movie
  E518: search
  E519: key
  E51A: boutique
  E520: faxto
  E521: mail
  E522: one
  E523: two
  E524: three
  E525: four
  E526: five
  E527: six
  E528: seven
  E529: eight
  E52A: nine
  E52C: mobaq
  E54C: upwardleft
  E54D: downwardright
  E54E: tm
  E555: upwardright
  E556: downwardleft
  E558: copyright
  E559: r-mark
  E55D: enter
  E571: gasstation
  E578: free
  E57A: watch
  E57D: yen
  E587: wrench
  E588: mobilephone
  E594: clock
  E595: heart01
  E596: telephone
  E597: cafe
  E598: mist
  E599: golf
  E59A: basketball
  E59B: pocketbell
  E59C: art
  E59E: event
  E59F: ribbon
  E5A0: birthday
  E5A1: spade
  E5A2: diamond
  E5A3: club
  E5A4: eye
  E5A5: ear
  E5A6: scissors
  E5A7: paper
  E5A8: newmoon
  E5A9: moon1
  E5AA: moon2
  E5AB: clear
  E5AC: zero
  E5AD: ok
  E5AE: wobbly
  E5B0: impact
  E5B1: sweat01
  E5B4: noodle
  E5B5: new
  E5B6: t-shirt
  E5B8: pc
  E5BC: subway
  E5BD: fuji
  E5BE: note
  E5C3: wink
  E5C4: lovely
  E5C5: shock
  E5C6: coldsweats02
  E5C9: crown
  E5DE: postoffice
  E5DF: hospital
  EA80: school
  EA81: hotel
  EA82: ship
  EA88: id
  EA89: full
  EA8A: empty
  EA92: memo
  EA97: bottle
  EAA5: heart
  EAAB: shine
  EAAC: ski
  EAAE: japanesetea
  EAAF: bread
  EAB9: apple
  EABF: catface
  EAC0: despair
  EAC2: bearing
  EAC3: sad
  EAC5: confident
  EAC9: gawk
  EACD: delicious
  EAE8: sprinkle
  EAF1: night
  EAF5: drama
  EB03: pen
  EB08: phoneto
  EB2A: foot
  EB2B: shoe
  EB2C: flag
  EB2D: up
  EB2E: down
  EB2F: sign02
  EB30: sign03
  EB31: sign05
  EB35: banana
  EB5D: pout
  EB62: mailto
  EB69: weep
  EB75: heart02
  EB77: denim
  EB78: loveletter
  EB79: recycle
  EB7A: leftright
  EB7B: updown
  EB7C: wave
  EB7D: bud
  EB7E: snail
  EB80: smile
  EB83: rock
  EB84: sharp
softbank:
  E003: kissmark
  E006: t-shirt
  E007: shoe
  E008: camera
  E009: telephone
  E00A: mobilephone
  E00B: faxto
  E00C: pc
  E00D: punch
  E00E: good
  E010: rock
  E011: scissors
  E012: paper
  E013: ski
  E014: golf
  E015: tennis
  E016: baseball
  E018: soccer
  E019: fish
  E01A: horse
  E01B: car
  E01C: yacht
  E01D: airplane
  E01E: train
  E021: sign01
  E022: heart01
  E023: heart03
  E02D: clock
  E030: cherryblossom
  E033: xmas
  E034: ring
  E036: house
  E038: building
  E03A: gasstation
  E03B: fuji
  E03C: karaoke
  E03D: movie
  E03E: note
  E03F: key
  E043: restaurant
  E044: wine
  E045: cafe
  E046: cake
  E047: beer
  E048: snow
  E049: cloud
  E04A: sun
  E04B: rain
  E04C: moon3
  E04F: cat
  E052: dog
  E055: penguin
  E056: delicious
  E057: happy01
  E058: despair
  E059: angry
  E103: loveletter
  E104: phoneto
  E105: bleah
  E106: lovely
  E107: shock
  E108: coldsweats02
  E10B: pig
  E10E: crown
  E10F: flair
  E110: clover
  E112: present
  E114: search
  E115: run
  E118: maple
  E11F: chair
  E120: fastfood
  E123: spa
  E125: ticket
  E126: cd
  E12A: tv
  E12F: dollar
  E132: motorsports
  E136: bicycle
  E13C: sleepy
  E13D: thunder
  E13E: boutique
  E148: book
  E14D: bank
  E14E: signaler
  E14F: parking
  E151: toilet
  E153: postoffice
  E154: atm
  E155: hospital
  E156: 24hours
  E157: school
  E158: hotel
  E159: bus
  E202: ship
  E208: nosmoking
  E20A: wheelchair
  E20C: heart
  E20D: diamond
  E20E: spade
  E20F: club
  E210: sharp
  E211: freedial
  E212: new
  E21C: one
  E21D: two
  E21E: three
  E21F: four
  E220: five
  E221: six
  E222: seven
  E223: eight
  E224: nine
  E225: zero
  E229: id
  E22A: full
  E22B: empty
  E236: up
  E237: upwardleft
  E238: downwardright
  E239: downwardleft
  E23F: aries
  E240: taurus
  E241: gemini
  E242: cancer
  E243: leo
  E244: virgo
  E245: libra
  E246: scorpius
  E247: sagittarius
  E248: capricornus
  E249: aquarius
  E24A: pisces
  E24D: ok
  E24E: copyright
  E24F: r-mark
  E252: danger
  E301: memo
  E304: tulip
  E30A: music
  E30B: bottle
  E30E: smoking
  E311: bomb
  E313: hairsalon
  E314: ribbon
  E315: secret
  E31C: rouge
  E323: bag
  E324: slate
  E325: bell
  E326: notes
  E327: heart04
  E32E: shine
  E330: dash
  E331: sweat02
  E334: annoy
  E338: japanesetea
  E339: bread
  E340: noodle
  E342: riceball
  E345: apple
  E34B: birthday
  E402: catface
  E403: think
  E404: smile
  E405: wink
  E406: wobbly
  E407: sad
  E40A: confident
  E40E: gawk
  E411: crying
  E413: weep
  E415: coldsweats01
  E416: pout
  E419: eye
  E41B: ear
  E42A: basketball
  E42E: rvcar
  E434: subway
  E435: bullettrain
  E43C: sprinkle
  E43E: wave
  E443: typhoon
  E44B: night
  E502: art
  E503: drama
  E523: chick
  E536: foot
  E537: tm
