development:
  set_server:
    - server: 127.0.0.1
      port: 1979
      role: write
test:
  set_server:
    - server: 127.0.0.1
      port: 1979
      role: write
production:
  set_server:
    - server: 127.0.0.1
      port: 1979
      role: write
log_file: log/miyazakiresistance.log
