cwd: <%= current_path %>
servers: <%= mongrel_servers %>
log_file:  <%= shared_path %>/log/mongrel.log
port: <%= mongrel_port %>
address: <%= mongrel_address %>
environment: <%= mongrel_environment %>
pid_file: <%= shared_path %>/pids/mongrel.pid
user: <%= mongrel_user %>
group: <%= mongrel_group %>
